export const PENDING = '_PENDING';
export const FULFILLED = '_FULFILLED';
export const REJECTED = '_REJECTED';
export const PROGRESS = '_PROGRESS';

export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_COACH_IDS = 'UPDATE_COACH_IDS';
export const UPDATE_CAMP_IDS = 'UPDATE_CAMP_IDS';
export const UPDATE_FITNESS_BUSINESS_IDS = 'UPDATE_FITNESS_BUSINESS_IDS';
export const UPDATE_OTHER_IDS = 'UPDATE_OTHER_IDS';
export const UPDATE_ATHLETE_IDS = 'UPDATE_ATHLETE_IDS';
export const UPDATE_PARENT_IDS = 'UPDATE_PARENT_IDS';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_COUNTRIES = 'SET_COUNTRIES';
export const ADD_COUNTRY = 'ADD_COUNTRY';
export const CLEAR_COUNTRIES = 'CLEAR_COUNTRIES';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const ADD_PICTURE = 'ADD_PICTURE';
export const UPDATE_PICTURE = 'ADD_PICTURE';
export const CLEAR_PICTURE = 'CLEAR_PICTURE';
export const SET_IMAGES = 'SET_IMAGES';
export const UPDATE_IMAGE = 'SET_IMAGE';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';
export const ADD_IMAGES = 'ADD_IMAGES';
export const CLEAR_IMAGES = 'CLEAR_IMAGES';
export const SET_VIDEOS = 'SET_VIDEOS';
export const REMOVE_VIDEO = 'REMOVE_VIDEO';
export const ADD_VIDEOS = 'ADD_VIDEOS';
export const UPDATE_VIDEO = 'UPDATE_VIDEO';
export const CLEAR_VIDEOS = 'CLEAR_VIDEOS';
export const UPDATE_SPORT = 'UPDATE_SPORT';
export const CLEAR_SPORTS = 'CLEAR_SPORTS';
export const UPDATE_SPECIALIZATION = 'UPDATE_SPECIALITY';
export const ADD_NEW_SPORT = 'ADD_NEW_SPORT';
export const UPDATE_CERTIFICATION = 'UPDATE_CERTIFICATION';
export const CLEAR_CERTIFICATIONS = 'CLEAR_CERTIFICATIONS';
export const ADD_NEW_CERTIFICATION = 'ADD_NEW_CERTIFICATION';
export const UPDATE_DEGREE = 'UPDATE_DEGREE';
export const CLEAR_DEGREES = 'CLEAR_DEGREES';
export const ADD_NEW_DEGREE = 'ADD_NEW_DEGREE';
export const UPDATE_SKILLLEVEL = 'UPDATE_SKILLLEVEL';
export const CLEAR_SKILLLEVELS = 'CLEAR_SKILLLEVELS';
export const UPDATE_AGE = 'UPDATE_AGE';
export const CLEAR_AGES = 'CLEAR_AGES';
export const UPDATE_GENDER = 'UPDATE_GENDER';
export const CLEAR_GENDER = 'CLEAR_GENDER';
export const UPDATE_TRAINING = 'UPDATE_TRAINING';
export const CLEAR_TRAINING = 'CLEAR_TRAINING';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const CLEAR_SERVICE = 'CLEAR_SERVICE';
export const UPDATE_LISTING = 'UPDATE_LISTING';
export const CLEAR_LISTING = 'CLEAR_LISTING';
export const ADD_SESSION = 'ADD_SESSION';
export const UPDATE_SESSION = 'UPDATE_SESSION';

export const CLEAR_SESSION = 'CLEAR_SESSION';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const CLEAR_ACCOUNT = 'CLEAR_ACCOUNT';
export const UPDATE_BOOKING_PREFERENCES = 'UPDATE_BOOKING_PREFERENCES';
export const CLEAR_BOOKING_PREFERENCES = 'CLEAR_BOOKING_PREFERENCES';
export const UPDATE_BUSINESS_MODEL = 'UPDATE_BUSINESS_MODEL';
export const CLEAR_BUSINESS_MODEL = 'CLEAR_BUSINESS_MODEL';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const CLEAR_EVENTS = 'CLEAR_EVENTS';
export const ADD_EVENTS = 'ADD_EVENTS';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const CLEAR_LOCATIONS = 'CLEAR_LOCATIONS';
export const ADD_LOCATION = 'ADD_LOCATION';
export const UPDATE_PAYOUT_OPTION = 'UPDATE_PAYOUT_OPTION';
export const CLEAR_PAYOUT_OPTION = 'CLEAR_PAYOUT_OPTION';
export const UPDATE_BANK_DETAILS = 'UPDATE_BANK_DETAILS';
export const CLEAR_BANK_DETAILS = 'CLEAR_BANK_DETAILS';
export const UPDATE_PAYPAL_DETAILS = 'UPDATE_PAYPAL_DETAILS';
export const CLEAR_PAYPAL_DETAILS = 'CLEAR_PAYPAL_DETAILS';
export const UPDATE_PRICE = 'UPDATE_PRICE';
export const CLEAR_PRICES = 'CLEAR_PRICES';
export const ADD_PRICE = 'ADD_PRICE';
export const UPDATE_TRAVEL_PREFERENCES = 'UPDATE_TRAVEL_PREFERENCES';
export const CLEAR_TRAVEL_PREFERENCES = 'CLEAR_TRAVEL_PREFERENCES';

export const UPDATE_AGES_PRICING = 'UPDATE_AGES_PRICING';
export const UPDATE_SKILLLEVELS_PRICING = 'UPDATE_SKILLLEVELS_PRICING';
export const ADD_AGES_PRICING = 'ADD_AGES_PRICING';
export const ADD_SKILLLEVELS_PRICING = 'ADD_SKILLLEVELS_PRICING';

export const ADD_MESSAGE_LABEL = 'ADD_MESSAGE_LABEL';
export const FETCH_MESSAGE_LABEL = 'FETCH_MESSAGE_LABEL';
export const DELETE_MESSAGE_LABEL = 'DELETE_MESSAGE_LABEL';
export const CLEAR_MESSAGE_LABELS = 'CLEAR_MESSAGE_LABELS';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const CLEAR_SENT_MESSAGE_STATUS = 'CLEAR_SENT_MESSAGE_STATUS';

export const FETCH_DRAFT_MESSAGES = 'FETCH_DRAFT_MESSAGES';
export const SAVE_MESSAGE_DRAFTS = 'SAVE_MESSAGE_DRAFT';
export const CLEAR_DRAFT_MESSAGE_STATUS = 'CLEAR_DRAFT_MESSAGE_STATUS';
export const CLEAR_DRAFT_MESSAGES = 'CLEAR_DRAFT_MESSAGES';

export const CHANGE_MESSAGING_PROFILE = 'CHANGE_MESSAGING_PROFILE';

export const UPDATE_MESSAGE_ATTACHMENT = 'UPDATE_MESSAGE_ATTACHMENT';
export const CANCEL_UPDATE_MESSAGE_ATTACHMENT = 'CANCEL_UPDATE_MESSAGE_ATTACHMENT';

export const ADD_DISCOUNT = 'ADD_DISCOUNT';

export const UPDATE_SESSION_NAME = 'UPDATE_SESSION_NAME';
export const CLEAR_SESSION_NAME = 'CLEAR_SESSION_NAME';

export const SET_STATES = 'SET_STATES';
export const ADD_STATE = 'ADD_STATE';
export const CLEAR_STATES = 'CLEAR_STATES';

export const UPDATE_BUSINESS = 'UPDATE_BUSINESS';
export const CLEAR_BUSINESS = 'CLEAR_BUSINESS';

export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const UPDATE_PHONES = 'UPDATE_PHONES';
export const ADD_PHONE = 'ADD_PHONE';
export const CLEAR_CONTACT = 'CLEAR_CONTACT';

export const SET_SESSIONS = 'SET_SESSIONS';
export const REMOVE_SESSION = 'REMOVE_SESSION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';

export const REMOVE_EVENT = 'REMOVE_EVENT';

export const ADD_SKILLLEVEL = 'ADD_SKILLLEVEL';
export const REMOVE_DISCOUNT = 'REMOVE_DISCOUNT';

export const FETCH_SELECTED_THREAD = 'FETCH_SELECTED_THREAD';
export const CLEAR_SELECTED_THREAD = 'CLEAR_SELECTED_THREAD';
export const FETCH_REWARDS = 'FETCH_REWARDS';
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_SPORTS = 'FETCH_SPORTS';
export const FETCH_SPORTS_LIST = 'FETCH_SPORTS_LIST';
export const FETCH_CERTIFICATIONS_LIST = 'FETCH_CERTIFICATIONS_LIST';
export const FETCH_DEGREES_LIST = 'FETCH_DEGREES_LIST';
export const FETCH_INSTITUTIONS_LIST = 'FETCH_INSTITUTIONS_LIST';
export const SET_LOCATIONS = 'SET_LOCATIONS';
export const SET_TRAINING = 'SET_TRAINING';
export const SET_SERVICE = 'SET_SERVICE';
export const SET_GENDER = 'SET_GENDER';
export const SET_AGES = 'SET_AGES';
export const SET_SKILLS = 'SET_SKILLS';
export const SET_PRICING = 'SET_PRICING';
export const SAVE_PRICE = 'SAVE_PRICE';
export const SET_SPORTS = 'SET_SPORTS';
export const SET_CERTIFICATIONS = 'SET_CERTIFICATIONS';
export const SET_DEGREE = 'SET_DEGREE';
export const SET_BUSINESS = 'SET_BUSINESS';
export const SET_LISTING = 'SET_LISTING';
export const FETCH_REWARDS_STATS = 'FETCH_REWARDS_STATS';
export const FETCH_SESSION_STATS = 'FETCH_SESSION_STATS';
export const FETCH_REVIEW_STATS = 'FETCH_REVIEW_STATS';
export const FETCH_EARNING_STATS = 'FETCH_EARNING_STATS';

export const UPDATE_PROFILE_DATA = 'UPDATE_PROFILE_DATA';

export const FETCH_USER_PROFILES = 'FETCH_USER_PROFILES';
export const CLEAR_USER_PROFILES = 'CLEAR_USER_PROFILES';

export const ARCHIVE_MESSAGE_THREAD = 'ARCHIVE_MESSAGE_THREAD';
export const TRASH_MESSAGE_THREAD = 'TRASH_MESSAGE_THREAD';
export const STAR_MESSAGE_THREAD = 'STAR_MESSAGE_THREAD';
export const UPDATE_MESSAGE_THREAD_LABELS = 'UPDATE_MESSAGE_THREAD_LABELS';

export const GET_UPDATED_SELECTED_THREAD = 'GET_UPDATED_SELECTED_THREAD';

export const LOCATION_URL_CHANGE = 'LOCATION_URL_CHANGE';
export const POST_PROFILE = 'POST_PROFILE';
export const SUCCESS = 'SUCCESS';

export const CLEAR_SPORTS_LIST = 'CLEAR_SPORTS_LIST';
export const SET_SPORTS_LIST = 'SET_SPORTS_LIST';
export const CLEAR_DEGREES_LIST = 'CLEAR_DEGREES_LIST';
export const SET_DEGREES_LIST = 'SETDEGREES_LIST';
export const CLEAR_INSTITUTIONS_LIST = 'CLEAR_INSTITUTIONS_LIST';
export const SET_INSTITUTIONS_LIST = 'SET_INSTITUTIONS_LIST';
export const CLEAR_CERTIFICATIONS_LIST = 'CLEAR_CERTIFICATIONS_LIST';
export const SET_CERTIFICATIONS_LIST = 'SET_CERTIFICATIONS_LIST';

export const FETCH_CANCELLATION_POLICIES = 'FETCH_CANCELLATION_POLICIES';
export const CLEAR_CANCELLATION_POLICIES = 'CLEAR_CANCELLATION_POLICIES';

export const FETCH_SKILLS_LIST = 'FETCH_SKILLS_LIST';
export const CLEAR_SKILLS_LIST = 'CLEAR_SKILLS_LIST';

export const FETCH_AGES_LIST = 'FETCH_AGES_LIST';
export const CLEAR_AGES_LIST = 'CLEAR_AGES_LIST';

export const FETCH_TRAINING_LIST = 'FETCH_TRAINING_LIST';
export const CLEAR_TRAINING_LIST = 'CLEAR_TRAINING_LIST';
export const FETCH_SERVICES_LIST = 'FETCH_SERVICES_LIST';
export const CLEAR_SERVICES_LIST = 'CLEAR_SERVICES_LIST';
export const INVITE_USERS = 'INVITE_USERS';
export const FETCH_REWARDS_HISTORY = 'FETCH_REWARDS_HISTORY';
export const FILTER_CHANGE_REWARDS_HISTORY = 'FILTER_CHANGE_REWARDS_HISTORY';
export const FETCH_USER_IDS = 'FETCH_USER_IDS';

export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_STATES = 'FETCH_STATES';

export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_SESSIONS = 'FETCH_SESSIONS';
export const FETCH_EVENTS = 'FETCH_EVENTS';

export const FETCH_MESSAGE_THREADS = 'FETCH_MESSAGE_THREADS';
export const FETCH_MESSAGES_METADATA = 'FETCH_MESSAGES_METADATA';

export const THREAD_LIST_PAGE_CHANGE = 'THREAD_LIST_PAGE_CHANGE';

export const POLYGLOT_SET_LANGUAGE = '@@polyglot/SET_LANGUAGE';

export const POLL_MESSAGES_METADATA = 'POLL_MESSAGES_METADATA';
export const POLL_SHOPPING_CART_DATA = 'POLL_SHOPPING_CART_DATA';
export const CANCEL_POLL_MESSAGES_METADATA = 'CANCEL_POLL_MESSAGES_METADATA';
export const CANCEL_SHOPPING_CART_DATA = 'CANCEL_SHOPPING_CART_DATA';
export const SET_RATING = 'SET_RATING';
export const UPDATE_OFFER_TERMINOLOGY = 'UPDATE_OFFER_TERMINOLOGY';

export const ACTIVATE_DISCOUNT = 'ACTIVATE_DISCOUNT';
export const UPDATE_CANCELLATION_POLICY = 'UPDATE_CANCELLATION_POLICY';
export const CLEAR_CANCELLATION_POLICY = 'CLEAR_CANCELLATION_POLICY';

export const UPDATE_CURRENCY = 'UPDATE_CURRENCY';
export const CLEAR_CURRENCY = 'CLEAR_CURRENCY';

export const SEARCH_MESSAGE_RECIPIENTS = 'SEARCH_MESSAGE_RECIPIENTS';
export const UPDATE_THREAD_READ_STATUS = 'UPDATE_THREAD_READ_STATUS';

export const VERIFY_NICKNAME = 'VERIFY_NICKNAME';
export const FETCH_NICKNAMES = 'FETCH_NICKNAMES';

export const UPDATE_DEFAULT_SESSION = 'UPDATE_DEFAULT_SESSION';
export const UPDATE_OVERRIDE_SESSION_LENGTH = 'UPDATE_OVERRIDE_SESSION_LENGTH';
export const UPDATE_OVERRIDE_BUFFER_LENGTH = 'UPDATE_OVERRIDE_BUFFER_LENGTH';
export const FETCH_TIMEZONES = 'FETCH_TIMEZONES';
export const SSP_SET_NICKNAME = 'SSP_SET_NICKNAME';

export const VALIDATE_BANK_PAYOUT_DETAILS = 'VALIDATE_BANK_PAYOUT_DETAILS';
export const SSP_BANK_PAYOUT_DETAILS_SUBMIT = 'SSP_BANK_PAYOUT_DETAILS_SUBMIT';
export const SSP_VALIDATE_PAYPAL_SETTINGS = 'SSP_VALIDATE_PAYPAL_SETTINGS';
export const SSP_PAYPAL_SETTINGS_SUBMIT = 'SSP_PAYPAL_SETTINGS_SUBMIT';
export const SSP_PAYOUT_DETAILS_SUBMIT = 'SSP_PAYOUT_DETAILS_SUBMIT';
export const SSP_VALIDATE_PAYOUT_DETAILS = 'SSP_VALIDATE_PAYOUT_DETAILS';
export const SSP_ACCOUNT_DETAILS_SUBMIT = 'SSP_ACCOUNT_DETAILS_SUBMIT';
export const SSP_VALIDATE_ACCOUNT_DETAILS = 'SSP_VALIDATE_ACCOUNT_DETAILS';
export const SSP_VALIDATE_BOOKING_PREFERENCE = 'SSP_VALIDATE_BOOKING_PREFERENCE';
export const SSP_BOOKING_PREFERENCE_SUBMIT = 'SSP_BOOKING_PREFERENCE_SUBMIT';
export const SSP_VALIDATE_BUSINESS_MODEL = 'SSP_VALIDATE_BUSINESS_MODEL';
export const SSP_BUSINESS_MODEL_SUBMIT = 'SSP_BUSINESS_MODEL_SUBMIT';
export const SSP_BUILD_PROFILE_SUBMIT = 'SSP_BUILD_PROFILE_SUBMIT';
export const SSP_VALIDATE_BUILD_PROFILE = 'SSP_VALIDATE_BUILD_PROFILE';
export const SSP_VALIDATE_TRAINING_PREFERENCE = 'SSP_VALIDATE_TRAINING_PREFERENCE';
export const SSP_TRAINING_PREFERENCE_SUBMIT = 'SSP_TRAINING_PREFERENCE_SUBMIT';

export const SSP_TRAINING_LOCATION_SUBMIT = 'SSP_TRAINING_LOCATION_SUBMIT';
export const SSP_VALIDATE_TRAINING_LOCATION = 'SSP_VALIDATE_TRAINING_LOCATION';

export const SSP_VALIDATE_TRAVEL_PREFERENCE = 'SSP_VALIDATE_TRAVEL_PREFERENCE';
export const SSP_TRAVEL_PREFERENCE_SUBMIT = 'SSP_TRAVEL_PREFERENCE_SUBMIT';
export const SSP_LISTING_SUBMIT = 'SSP_LISTING_SUBMIT';
export const SSP_VALIADATE_LISTING = 'SSP_VALIADATE_LISTING';
export const SSP_VALIDATE_PHOTOS_AND_VIDEOS = 'SSP_VALIDATE_PHOTOS_AND_VIDEOS';
export const SSP_PHOTOS_AND_VIDEOS_SUBMIT = 'SSP_PHOTOS_AND_VIDEOS_SUBMIT';

export const SSP_VALIDATE_SESSION_NAME = 'SSP_VALIDATE_SESSION_NAME';
export const SSP_SESSION_NAME_SUBMIT = 'SSP_SESSION_NAME_SUBMIT';
export const SSP_VALIDATE_SESSION = 'SSP_VALIDATE_SESSION';
export const SSP_SESSION_SUBMIT = 'SSP_SESSION_SUBMIT';

export const SSP_VALIDATE_EVENTS = 'SSP_VALIDATE_EVENTS';
export const SSP_SUBMIT_EVENTS = 'SSP_SUBMIT_EVENTS';

export const DELETE_MESSAGE_ATTACHMENT = 'DELETE_MESSAGE_ATTACHMENT';
export const SSP_VALIDATE_DISCOUNT = 'SSP_VALIDATE_DISCOUNT';
export const SSP_DISCOUNT_SUBMIT = 'SSP_DISCOUNT_SUBMIT';
export const RESET_DISCOUNT = 'RESET_DISCOUNT';
export const SET_NEW_PROFILE = 'SET_NEW_PROFILE';
export const CREATE_NEW_PROFILE = 'CREATE_NEW_PROFILE';

export const SSP_VALIDATE_PRICING = 'SSP_VALIDATE_PRICING';
export const SSP_VALIDATE_MULTIPLE_PRICING = 'SSP_VALIDATE_MULTIPLE_PRICING';
export const SSP_PRICING_SUBMIT = 'SSP_PRICING_SUBMIT';
export const CHANGE_PROFILE_UPDATE_STATUS = 'CHANGE_PROFILE_UPDATE_STATUS';
export const UPLOAD_ACTION_PICTURES = 'UPLOAD_ACTION_PICTURES';
export const SET_ACTION_PICTURES = 'SET_ACTION_PICTURES';
export const DELETE_ACTION_PICTURE = 'DELETE_ACTION_PICTURE';
export const UPDATE_ACTION_PICTURE = 'UPDATE_ACTION_PICTURE';
export const UPLOAD_ACTION_VIDEOS = 'UPLOAD_ACTION_VIDEOS';
export const SET_ACTION_VIDEOS = 'SET_ACTION_VIDEOS';
export const DELETE_ACTION_VIDEO = 'DELETE_ACTION_VIDEO';
export const ACTION_VIDEOS_UPLOAD_PROGRESS = 'ACTION_VIDEOS_UPLOAD_PROGRESS';
export const UPDATE_NICKNAME = 'UPDATE_NICKNAME';
export const SSP_SET_PRESENT_NICKNAME = 'SSP_SET_PRESENT_NICKNAME';
export const SET_DISPLAY_PICTURE = 'SET_DISPLAY_PICTURE';
export const POST_ACTION_IMAGES = 'POST_ACTION_IMAGES';
export const POST_ACTION_VIDEOS = 'POST_ACTION_VIDEOS';
export const SET_CITIES = 'SET_CITIES';
export const FETCH_CITIES = 'FETCH_CITIES';
export const ADD_CITIES = 'ADD_CITIES';
export const CLEAR_CITIES = 'CLEAR_CITIES';

export const SSP_VALIDATE_TRAINING_LOCATIONS = 'SSP_VALIDATE_TRAINING_LOCATIONS';
export const SSP_TRAINING_LOCATIONS_SUBMIT = 'SSP_TRAINING_LOCATIONS_SUBMIT';
export const SET_PAYPAL_VERIFICATION_STATUS = 'SET_PAYPAL_VERIFICATION_STATUS';
export const VERIFY_PAYAPAL_EMAIL = 'VERIFY_PAYAPAL_EMAIL';
export const VERIFY_PAYAPAL_PIN = 'VERIFY_PAYAPAL_PIN';
export const FETCH_GEO_LOCATION = 'FETCH_GEO_LOCATION';
export const FETCH_TIMEZONE = 'FETCH_TIMEZONE';

export const UPDATE_CURRENT_SPORT = 'UPDATE_CURRENT_SPORT';
export const SET_CURRENT_SPORT = 'SET_CURRENT_SPORT';
export const CLEAR_CURRENT_SPORT = 'CLEAR_CURRENT_SPORT';

export const UPDATE_CURRENT_TERMINOLOGY = 'UPDATE_CURRENT_TERMINOLOGY';
export const UPDATE_CURRENT_SPECIALIZATIONS = 'UPDATE_CURRENT_SPECIALIZATIONS';

export const UPDATE_UNI_DEGREE = 'UPDATE_UNI_DEGREE';
export const CLEAR_UNI_DEGREE = 'CLEAR_UNI_DEGREE';
export const NEW_DEGREE_VALIDATION = 'NEW_DEGREE_VALIDATION';
export const NEW_DEGREE_SUBMIT = 'NEW_DEGREE_SUBMIT';
export const ADD_DEGREE = 'ADD_DEGREE';

export const FETCH_CURRENT_SPORT = 'FETCH_CURRENT_SPORT';
export const DELETE_SPORT = 'DELETE_SPORT';
export const POST_CURRENT_SPORT = 'POST_CURRENT_SPORT';
export const ADD_NEW_DEGREE_TO_DB = 'ADD_NEW_DEGREE_TO_DB';
export const ADD_NEW_INSTITUTION_TO_DB = 'ADD_NEW_INSTITUTION_TO_DB';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const DEACTIVATE_ACCOUNT = 'DEACTIVATE_ACCOUNT';

export const SET_SPORTS_DEGREE = 'SET_SPORTS_DEGREE';
export const ADD_SPORTS_DEGREE = 'ADD_SPORTS_DEGREE';
export const CLEAR_SPORTS_DEGREES = 'CLEAR_SPORTS_DEGREES';
export const REMOVE_SPORTS_DEGREE = 'REMOVE_SPORTS_DEGREE';
export const REMOVE_UNI_DEGREE = 'REMOVE_UNI_DEGREE';
export const FETCH_GEN_CERTIFICATIONS_LIST = 'FETCH_GEN_CERTIFICATIONS_LIST';
export const CLEAR_GEN_CERTIFICATIONS_LIST = 'CLEAR_GEN_CERTIFICATIONS_LIST';
export const UPDATE_NEW_CERTIFICATION = 'UPDATE_NEW_CERTIFICATION';
export const CLEAR_NEW_CERTIFICATION = 'CLEAR_NEW_CERTIFICATION';
export const ADD_NEW_CERTIFICATION_TO_DB = 'ADD_NEW_CERTIFICATION_TO_DB';
export const ADD_NEW_GEN_CERTIFICATION = 'ADD_NEW_GEN_CERTIFICATION';
export const SET_GEN_CERTIFICATIONS = 'SET_GEN_CERTIFICATIONS';
export const REMOVE_GEN_CERTIFICATION = 'REMOVE_GEN_CERTIFICATION';
export const CLEAR_GEN_CERTIFICATIONS = 'CLEAR_GEN_CERTIFICATIONS';
export const NEW_CERTIFICATION_VALIDATION = 'NEW_CERTIFICATION_VALIDATION';
export const NEW_CERTIFICATION_SUBMIT = 'NEW_CERTIFICATION_SUBMIT';
export const ADD_NEW_SPORT_CERTIFICATION = 'ADD_NEW_SPORT_CERTIFICATION';
export const REMOVE_SPORT_CERTIFICATION = 'REMOVE_SPORT_CERTIFICATION';
export const CLEAR_NEW_CERTIFICATION_VALIDATION = 'CLEAR_NEW_CERTIFICATION_VALIDATION';
export const FETCH_GEN_AWARDS_LIST = 'FETCH_GEN_AWARDS_LIST';
export const CLEAR_GEN_AWARDS_LIST = 'CLEAR_GEN_AWARDS_LIST';
export const UPDATE_UNI_AWARD = 'UPDATE_UNI_AWARD';
export const CLEAR_UNI_AWARD = 'CLEAR_UNI_AWARD';
export const NEW_AWARD_VALIDATION = 'NEW_AWARD_VALIDATION';
export const NEW_AWARD_SUBMIT = 'NEW_AWARD_SUBMIT';
export const CLEAR_NEW_AWARDS_VALIDATION = 'CLEAR_NEW_AWARDS_VALIDATION';
export const ADD_NEW_GEN_AWARD = 'ADD_NEW_GEN_AWARD';
export const SET_GEN_AWARDS = 'SET_GEN_AWARDS';
export const CLEAR_GEN_AWARDS = 'CLEAR_GEN_AWARDS';
export const REMOVE_GEN_AWARD = 'REMOVE_GEN_AWARD';
export const SET_SPORTS_AWARDS = 'SET_SPORTS_AWARDS';
export const ADD_SPORTS_AWARD = 'ADD_SPORTS_AWARD';
export const REMOVE_SPORTS_AWARD = 'REMOVE_SPORTS_AWARD';
export const CLEAR_SPORTS_AWARDS = 'CLEAR_SPORTS_AWARDS';
export const SET_SPORTS_AWARDS_LIST = 'SET_SPORTS_AWARDS_LIST';
export const CLEAR_SPORTS_AWARDS_LIST = 'CLEAR_SPORTS_AWARDS_LIST';
export const ADD_NEW_AWARD_TO_DB = 'ADD_NEW_AWARD_TO_DB';
export const FETCH_AFFILIATION_LIST = 'FETCH_AFFILIATION_LIST';
export const FETCH_SPORTS_AFFILIATION_LIST = 'FETCH_SPORTS_AFFILIATION_LIST';
export const UPDATE_NEW_AFFILIATION = 'UPDATE_NEW_AFFILIATION';
export const CLEAR_NEW_AFFILIATION = 'CLEAR_NEW_AFFILIATION';
export const SET_GEN_AFFILIATION = 'SET_GEN_AFFILIATION';
export const SET_SPORTS_AFFILIATION = 'SET_SPORTS_AFFILIATION';
export const ADD_NEW_GEN_AFFILIATION = 'ADD_NEW_GEN_AFFILIATION';
export const ADD_NEW_SPORTS_AFFILIATION = 'ADD_NEW_SPORTS_AFFILIATION';
export const REMOVE_GEN_AFFILIATION = 'REMOVE_GEN_AFFILIATION';
export const REMOVE_SPORTS_AFFILIATION = 'REMOVE_SPORTS_AFFILIATION';
export const CLEAR_GEN_AFFILIATION = 'CLEAR_GEN_AFFILIATION';
export const CLEAR_SPORTS_AFFILIATION = 'CLEAR_SPORTS_AFFILIATION';
export const FETCH_TOOLS_LIST = 'FETCH_TOOLS_LIST';
export const FETCH_SPORTS_TOOLS_LIST = 'FETCH_SPORTS_TOOLS_LIST';
export const UPDATE_NEW_TOOLS = 'UPDATE_NEW_TOOLS';
export const CLEAR_NEW_TOOLS = 'CLEAR_NEW_TOOLS';
export const ADD_NEW_GEN_TOOL = 'ADD_NEW_GEN_TOOL';
export const ADD_NEW_SPORT_TOOL = 'ADD_NEW_SPORT_TOOL';
export const SET_GEN_TOOLS = 'SET_GEN_TOOLS';
export const SET_SPORTS_TOOLS = 'SET_SPORTS_TOOLS';
export const REMOVE_GEN_TOOL = 'REMOVE_GEN_TOOL';
export const REMOVE_SPORTS_TOOL = 'REMOVE_SPORTS_TOOL';
export const CLEAR_GEN_TOOLS = 'CLEAR_GEN_TOOLS';
export const CLEAR_SPORTS_TOOL = 'CLEAR_SPORTS_TOOL';
export const ADD_NEW_TOOL_TO_DB = 'ADD_NEW_TOOL_TO_DB';
export const SET_SPORTS_TOOL_LIST = 'SET_SPORTS_TOOL_LIST';
export const FETCH_GEN_TOOL_LIST = 'FETCH_GEN_TOOL_LIST';
export const CLEAR_GEN_TOOLS_LIST = 'CLEAR_GEN_TOOLS_LIST';
export const CLEAR_SPORTS_TOOLS_LIST = 'CLEAR_SPORTS_TOOLS_LIST';
export const NEW_TOOL_VALIDATION = 'NEW_TOOL_VALIDATION';
export const NEW_TOOL_SUBMIT = 'NEW_TOOL_SUBMIT';
export const CLEAR_NEW_TOOL_VALIDATION = 'CLEAR_NEW_TOOL_VALIDATION';
export const NEW_SPORTS_TOOL_VALIDATION = 'NEW_SPORTS_TOOL_VALIDATION';
export const NEW_SPORTS_TOOL_SUBMIT = 'NEW_SPORTS_TOOL_SUBMIT';
export const CLEAR_NEW_SPORTS_TOOL_VALIDATION = 'CLEAR_NEW_SPORTS_TOOL_VALIDATION';
export const UPDATE_NEW_SPORTS_TOOLS = 'UPDATE_NEW_SPORTS_TOOLS';
export const SET_SPORTS_DEGREE_LIST = 'SET_SPORTS_DEGREE_LIST';
export const CLEAR_SPORTS_DEGREES_LIST = 'CLEAR_SPORTS_DEGREES_LIST';
export const POST_SESSIONS = 'POST_SESSIONS';
export const DELETE_SESSION = 'DELETE_SESSION';
export const CHANGE_SPORT_UPDATE_STATUS = 'CHANGE_SPORT_UPDATE_STATUS';

export const POST_EVENTS = 'POST_EVENTS';
export const DELETE_EVENT = 'DELETE_EVENT';
export const SET_SPORTS_STORE = 'SET_SPORTS_STORE';
export const SET_TRAVEL_PREFERENCES = 'SET_TRAVEL_PREFERENCES';
export const SET_CONTACT = 'SET_CONTACT';
export const SET_BUSINESS_MODEL = 'SET_BUSINESS_MODEL';
export const SET_BOOKING_PREFERENCES = 'SET_BOOKING_PREFERENCES';
export const SET_CANCELATION_POLICY = 'SET_CANCELATION_POLICY';
export const SET_PAYOUT_OPTION = 'SET_PAYOUT_OPTION';
export const SET_CURRENCY = 'SET_CURRENCY';
export const SET_BANK_DETAILS = 'SET_BANK_DETAILS';
export const SET_PAYPAL_DETAILS = 'SET_PAYPAL_DETAILS';

export const SAVE_DATA_ON_NEXT = 'SAVE_DATA_ON_NEXT';
export const CLEAR_SAVE_DATA_ON_NEXT = 'CLEAR_SAVE_DATA_ON_NEXT';

export const ACTIVATE_NEW_PROFILE = 'ACTIVATE_NEW_PROFILE';
export const CHANGE_PROFILE_ACTIVATION_STATUS = 'CHANGE_PROFILE_ACTIVATION_STATUS';

export const CLEAR_SESSION_VALIDATION = 'CLEAR_SESSION_VALIDATION';
export const DELETE_DISCOUNT = 'DELETE_DISCOUNT';
export const SAVE_TRINING_PREFERENCES = 'SAVE_TRINING_PREFERENCES';
export const SAVE_BUILD_PROFILE = 'SAVE_BUILD_PROFILE';
export const SAVE_TRAINING_LOCATIONS = 'SAVE_TRAINING_LOCATIONS';
export const SAVE_BIOGRAPHY = 'SAVE_BIOGRAPHY';
export const SAVE_BUSINESS_MODEL = 'SAVE_BUSINESS_MODEL';
export const SAVE_BOOKING_PREFERENCE = 'SAVE_BOOKING_PREFERENCE';
export const SAVE_ACCOUNT_DETAILS = 'SAVE_ACCOUNT_DETAILS';
export const SAVE_BANK_PAYOUT_DETAILS = 'SAVE_BANK_PAYOUT_DETAILS';
export const SAVE_PAYOUT_OPTION = 'SAVE_PAYOUT_OPTION';
export const CHANGE_UPLOAD_ACTION_PICTURE_STATUS = 'CHANGE_UPLOAD_ACTION_PICTURE_STATUS';
export const ISP_POST_REVIEW_MASTER = 'ISP_POST_REVIEW_MASTER';
export const SET_PAGE_STATUS = 'SET_PAGE_STATUS';
export const CLEAR_SPORTS_RELATED_STORES = 'CLEAR_SPORTS_RELATED_STORES';
export const FETCH_PROFILE_SPORTS_MAPPING = 'FETCH_PROFILE_SPORTS_MAPPING';
export const CHANGE_CURRENT_SPORT = 'CHANGE_CURRENT_SPORT';
export const ACTIVATE_SPORT = 'ACTIVATE_SPORT';
export const DEACTIVATE_SPORT = 'DEACTIVATE_SPORT';

export const SAVE_PARENT_PROFILE = 'SAVE_PARENT_PROFILE';
export const SAVE_PARENT_PREFERENCES = 'SAVE_PARENT_PREFERENCES';
export const SAVE_PARENT_ACCOUNT = 'SAVE_PARENT_ACCOUNT';

export const FETCH_PARENT_ORDER_HISTORY = 'FETCH_PARENT_ORDER_HISTORY';

export const FETCH_PARENT_PROFILE = 'FETCH_PARENT_PROFILE';
export const CLEAR_PARENT_PROFILE = 'CLEAR_PARENT_PROFILE';
export const SET_PARENT_PROFILE = 'SET_PARENT_PROFILE';

export const FETCH_PARENT_PREFERENCES = 'FETCH_PARENT_PREFERENCES';
export const CLEAR_PARENT_PREFERENCES = 'CLEAR_PARENT_PREFERENCES';
export const SET_PARENT_PREFERENCES = 'SET_PARENT_PREFERENCES';

export const FETCH_PARENT_ACCOUNT = 'FETCH_PARENT_ACCOUNT';
export const CLEAR_PARENT_ACCOUNT = 'CLEAR_PARENT_ACCOUNT';
export const SET_PARENT_ACCOUNT = 'SET_PARENT_ACCOUNT';

export const ADD_CHILD_PICTURE = 'ADD_CHILD_PICTURE';
export const SET_CHILD_PICTURE = 'SET_CHILD_PICTURE';
export const SAVE_PARENT_SHORT_PROFILE = 'SAVE_PARENT_SHORT_PROFILE';

export const FETCH_PARENT_ORDER_DETAILS = 'FETCH_PARENT_ORDER_DETAILS';
export const SAVE_ATHLETE_PROFILE = 'SAVE_ATHLETE_PROFILE';
export const SAVE_ATHLETE_PREFERENCES = 'SAVE_ATHLETE_PREFERENCES';
export const SAVE_ATHLETE_ACCOUNT = 'SAVE_ATHLETE_ACCOUNT';

export const FETCH_ATHLETE_ORDER_HISTORY = 'FETCH_ATHLETE_ORDER_HISTORY';

export const FETCH_SESSIONS_NEW = 'FETCH_SESSIONS_NEW';

export const FETCH_SCHEDULE_SESSIONS = 'FETCH_SCHEDULE_SESSIONS';
export const UPDATE_SCHEDULE_SESSIONS = 'UPDATE_SCHEDULE_SESSIONS';
export const CLEAR_SCHEDULE_SESSIONS = 'CLEAR_SCHEDULE_SESSIONS';
export const ADD_SCHEDULE_SESSIONS = 'ADD_SCHEDULE_SESSIONS';
export const REMOVE_SCHEDULE_SESSIONS = 'REMOVE_SCHEDULE_SESSIONS';

export const FETCH_MANAGE_BOOKINGS = 'FETCH_MANAGE_BOOKINGS';
export const UPDATE_MANAGE_BOOKINGS = 'UPDATE_MANAGE_BOOKINGS';
export const CLEAR_MANAGE_BOOKINGS = 'CLEAR_MANAGE_BOOKINGS';
export const ADD_MANAGE_BOOKINGS = 'ADD_MANAGE_BOOKINGS';
export const REMOVE_MANAGE_BOOKINGS = 'REMOVE_MANAGE_BOOKINGS';

export const FETCH_SESSION_HISTORY = 'FETCH_SESSION_HISTORY';
export const UPDATE_SESSION_HISTORY = 'UPDATE_SESSION_HISTORY';
export const CLEAR_SESSION_HISTORY = 'CLEAR_SESSION_HISTORY';
export const ADD_SESSION_HISTORY = 'ADD_SESSION_HISTORY';
export const REMOVE_SESSION_HISTORY = 'REMOVE_SESSION_HISTORY';
export const FETCH_ORDER_DETAILS = 'FETCH_ORDER_DETAILS';

export const FETCH_ATHLETE_PROFILE = 'FETCH_ATHLETE_PROFILE';
export const CLEAR_ATHLETE_PROFILE = 'CLEAR_ATHLETE_PROFILE';
export const SET_ATHLETE_PROFILE = 'SET_ATHLETE_PROFILE';

export const FETCH_ATHLETE_PREFERENCES = 'FETCH_ATHLETE_PREFERENCES';
export const CLEAR_ATHLETE_PREFERENCES = 'CLEAR_ATHLETE_PREFERENCES';
export const SET_ATHLETE_PREFERENCES = 'SET_ATHLETE_PREFERENCES';

export const FETCH_ATHLETE_ACCOUNT = 'FETCH_ATHLETE_ACCOUNT';
export const CLEAR_ATHLETE_ACCOUNT = 'CLEAR_ATHLETE_ACCOUNT';
export const SET_ATHLETE_ACCOUNT = 'SET_ATHLETE_ACCOUNT';
export const CREATE_NEW_ROLE = 'CREATE_NEW_ROLE';

export const ADD_ATHLETE_PICTURE = 'ADD_ATHLETE_PICTURE';
export const SET_ATHLETE_PICTURE = 'SET_ATHLETE_PICTURE';

export const ATHLETE_FETCH_SCHEDULED_SESSIONS = 'ATHLETE_FETCH_SCHEDULED_SESSIONS';

export const CREATE_NEW_SCHEDULED_SESSION = 'CREATE_NEW_SCHEDULED_SESSION';
export const CREATE_NEW_SCHEDULED_SESSION_STATUS = 'CREATE_NEW_SCHEDULED_SESSION_STATUS';
export const SS_RE_SCHEDULE_SESSION = 'SS_RE_SCHEDULE_SESSION';
export const ISP_SCHEDULES_SESSION_CHANGE_LOCATION = 'ISP_SCHEDULES_SESSION_CHANGE_LOCATION';
export const ISP_FETCH_LOCATION = 'ISP_FETCH_LOCATION';
export const SS_CHANGE_LOCATION_STATUS = 'SS_CHANGE_LOCATION_STATUS';
export const ISP_INVITE_ATHLETE = 'ISP_INVITE_ATHLETE';
export const ISP_SEARCH_ATHLETE = 'ISP_SEARCH_ATHLETE';
export const SS_INVITE_ATHLETE_STATUS = 'SS_INVITE_ATHLETE_STATUS';
export const ISS_ADD_SESSION_NOTES = 'SS_SESSION_NOTES';
export const SS_SESSION_NOTES_STATUS = 'SS_SESSION_NOTES_STATUS';
export const ISP_UPDATE_OVERIDE_PRICE = 'ISP_UPDATE_OVERIDE_PRICE';
export const SS_OVERIDE_PRICE_STATUS = 'SS_OVERIDE_PRICE_STATUS';
export const ISP_UPDATE_SESSION_BUFFER = 'ISP_UPDATE_SESSION_BUFFER';
export const ISP_UPDATE_TOTAL_SLOTS = 'ISP_UPDATE_TOTAL_SLOTS';
export const SS_SESSION_BUFFER_STATUS = 'SS_SESSION_BUFFER_STATUS';
export const ISP_REPEAT_SESSION = 'ISP_REPEAT_SESSION';
export const SS_REPEAT_SESSION_STATUS = 'SS_REPEAT_SESSION_STATUS';
export const ISP_CANCEL_SCHEDULED_SESSION = 'ISP_CANCEL_SCHEDULED_SESSION';
export const SS_CANCEL_SESSION_STATUS = 'SS_CANCEL_SESSION_STATUS';
export const FETCH_ISP_SCHEDULE_SETTINGS = 'FETCH_ISP_SCHEDULE_SETTINGS';
export const UPDATE_ISP_SCHEDULE_SETTINGS = 'UPDATE_ISP_SCHEDULE_SETTINGS';
export const SS_CANCEL_SCHEDULE_SETTINGS = 'SS_CANCEL_SCHEDULE_SETTINGS';
export const ISP_REMOVE_SCHEDULE = 'ISP_REMOVE_SCHEDULE';

export const ISP_UPDATE_SESSION_TOTAL_SLOTS = 'ISP_UPDATE_SESSION_TOTAL_SLOTS';
export const ISP_FETCH_SESSION_GROUP_SIZE = 'ISP_FETCH_SESSION_GROUP_SIZE';
export const ISP_UPDATE_SESSION_GROUP_SIZE = 'ISP_UPDATE_SESSION_GROUP_SIZE';

export const SAVE_ATHLETE_SHORT_PROFILE = 'SAVE_ATHLETE_SHORT_PROFILE';

export const ATHLETE_FETCH_ORDER_SESSIONS = 'ATHLETE_FETCH_ORDER_SESSIONS';
export const ATHLETE_FETCH_AVAILABLE_SLOTS = 'ATHLETE_FETCH_AVAILABLE_SLOTS';
export const ATHLETE_SCHEDULE_SESSION = 'ATHLETE_SCHEDULE_SESSION';
export const ATHLETE_RESCHEDULE_SESSION = 'ATHLETE_RESCHEDULE_SESSION';
export const ATHLETE_FETCH_UNSCHEDULE_SESSION = 'ATHLETE_FETCH_UNSCHEDULE_SESSION';
export const ATHLETE_FETCH_SESSION_HISTORY = 'ATHLETE_FETCH_SESSION_HISTORY';
export const ATHLETE_REPORT_INSTRUCTOR = 'ATHLETE_REPORT_INSTRUCTOR';
export const FETCH_VOLUME_DISCOUNTS = 'FETCH_VOLUME_DISCOUNTS';
export const ATHLETE_CANCEL_FUTURE_SESSIONS = 'ATHLETE_CANCEL_FUTURE_SESSIONS';
export const ATHLETE_FETCH_SCHEDULE_CHANGES = 'ATHLETE_FETCH_SCHEDULE_CHANGES';
export const ATHLETE_CANCEL_SESSION = 'ATHLETE_CANCEL_SESSION';
export const ATHLETE_FETCH_SESSIONS_COUNT = 'ATHLETE_FETCH_SESSIONS_COUNT';

export const FETCH_SPORTS_DEGREES_LIST = 'FETCH_SPORTS_DEGREES_LIST';
export const FETCH_SPORTS_CERTIFICATIONS_LIST = 'FETCH_SPORTS_CERTIFICATIONS_LIST';
export const CLEAR_SPORTS_CERTIFICATIONS_LIST = 'CLEAR_SPORTS_CERTIFICATIONS_LIST';
export const FETCH_SPORTS_AWARDS_LIST = 'FETCH_SPORTS_AWARDS_LIST';
export const ATHLETE_FETCH_FUTURE_SESSIONS = 'ATHLETE_FETCH_FUTURE_SESSIONS';
export const ATHLETE_REQUEST_REFUND = 'ATHLETE_REQUEST_REFUND';

export const ISP_REVIEW_MASTER = 'ISP_REVIEW_MASTER';
export const CHANGE_PROFILE = 'CHANGE_PROFILE';
export const FETCH_REASONS = 'FETCH_REASONS';
export const CLEAR_REASONS = 'CLEAR_REASONS';

export const EXPORT_ORDER_HISTORY = 'EXPORT_ORDER_HISTORY';

export const FETCH_ISP_TRAINED_ATHLETES = 'FETCH_SSP_TRAINED_ATHLETES';

export const FETCH_ISP_SESSION_DETAILS = 'FETCH_ISP_SESSION_DETAILS';
export const AWARDS = 'AWARDS';
export const ACCOMPLISHMENTS = 'ACCOMPLISHMENTS';
export const CERTIFICATIONS = 'CERTIFICATIONS';
export const DEGREES = 'DEGREES';
export const AFFILIATIONS = 'AFFILIATIONS';
export const EXPERIENCE = 'EXPERIENCE';
export const TOOLS = 'TOOLS';
export const TEACHING_TOOLS = 'TEACHING_TOOLS';
export const TRAINING_TOOLS = 'TRAINING_TOOLS';

export const FETCH_GEN_AWARDS = 'FETCH_GEN_AWARDS';
export const FETCH_GEN_AFFILIATIONS = 'FETCH_GEN_AFFILIATIONS';
export const FETCH_GEN_CERTIFICATIONS = 'FETCH_GEN_CERTIFICATIONS';
export const FETCH_GEN_TOOLS = 'FETCH_GEN_TOOLS';
export const FETCH_GEN_DEGREES = 'FETCH_GEN_DEGREES';
export const FETCH_GEN_EXPERIENCE = 'FETCH_GEN_EXPERIENCE';
export const FETCH_GEN_EXPERIENCE_YEAR = 'FETCH_GEN_EXPERIENCE_YEAR';
export const FETCH_GEN_ACCOMPLISHMENTS = 'FETCH_GEN_ACCOMPLISHMENTS';

export const FETCH_SPORT_AWARDS = 'FETCH_SPORT_AWARDS';
export const FETCH_SPORT_AFFILIATIONS = 'FETCH_SPORT_AFFILIATIONS';
export const FETCH_SPORT_CERTIFICATIONS = 'FETCH_SPORT_CERTIFICATIONS';
export const FETCH_SPORT_TOOLS = 'FETCH_SPORT_TOOLS';
export const FETCH_SPORT_DEGREES = 'FETCH_SPORT_DEGREES';
export const FETCH_SPORT_EXPERIENCE = 'FETCH_SPORT_EXPERIENCE';
export const FETCH_SPORT_EXPERIENCE_YEAR = 'FETCH_SPORT_EXPERIENCE_YEAR';
export const FETCH_SPORT_ACCOMPLISHMENTS = 'FETCH_SPORT_ACCOMPLISHMENTS';

export const SAVE_GEN_AWARD = 'SAVE_GEN_AWARD';
export const SAVE_GEN_AFFILIATION = 'SAVE_GEN_AFFILIATION';
export const SAVE_GEN_CERTIFICATION = 'SAVE_GEN_CERTIFICATION';
export const SAVE_GEN_TOOL = 'SAVE_GEN_TOOL';
export const SAVE_GEN_DEGREE = 'SAVE_GEN_DEGREE';
export const SAVE_GEN_EXPERIENCE = 'SAVE_GEN_EXPERIENCE';
export const SAVE_GEN_EXPERIENCE_YEAR = 'SAVE_GEN_EXPERIENCE_YEAR';
export const SAVE_GEN_ACCOMPLISHMENT = 'SAVE_GEN_ACCOMPLISHMENT';

export const SAVE_SPORT_AWARD = 'SAVE_SPORT_AWARD';
export const SAVE_SPORT_AFFILIATION = 'SAVE_SPORT_AFFILIATION';
export const SAVE_SPORT_CERTIFICATION = 'SAVE_SPORT_CERTIFICATION';
export const SAVE_SPORT_TOOL = 'SAVE_SPORT_TOOL';
export const SAVE_SPORT_DEGREE = 'SAVE_SPORT_DEGREE';
export const SAVE_SPORT_EXPERIENCE = 'SAVE_SPORT_EXPERIENCE';
export const SAVE_SPORT_EXPERIENCE_YEAR = 'SAVE_SPORT_EXPERIENCE_YEAR';
export const SAVE_SPORT_ACCOMPLISHMENT = 'SAVE_SPORT_ACCOMPLISHMENT';

export const DELETE_GEN_AWARD = 'DELETE_GEN_AWARD';
export const DELETE_GEN_AFFILIATION = 'DELETE_GEN_AFFILIATION';
export const DELETE_GEN_CERTIFICATION = 'DELETE_GEN_CERTIFICATION';
export const DELETE_GEN_TOOL = 'DELETE_GEN_TOOL';
export const DELETE_GEN_DEGREE = 'DELETE_GEN_DEGREE';
export const DELETE_GEN_EXPERIENCE = 'DELETE_GEN_EXPERIENCE';
export const DELETE_GEN_EXPERIENCE_YEAR = 'DELETE_GEN_EXPERIENCE_YEAR';
export const DELETE_GEN_ACCOMPLISHMENT = 'DELETE_GEN_ACCOMPLISHMENT';

export const DELETE_SPORT_AWARD = 'DELETE_SPORT_AWARD';
export const DELETE_SPORT_AFFILIATION = 'DELETE_SPORT_AFFILIATION';
export const DELETE_SPORT_CERTIFICATION = 'DELETE_SPORT_CERTIFICATION';
export const DELETE_SPORT_TOOL = 'DELETE_SPORT_TOOL';
export const DELETE_SPORT_DEGREE = 'DELETE_SPORT_DEGREE';
export const DELETE_SPORT_EXPERIENCE = 'DELETE_SPORT_EXPERIENCE';
export const DELETE_SPORT_EXPERIENCE_YEAR = 'DELETE_SPORT_EXPERIENCE_YEAR';
export const DELETE_SPORT_ACCOMPLISHMENT = 'DELETE_SPORT_ACCOMPLISHMENT';

export const COACHING_EXPERIENCE = 'COACHING_EXPERIENCE';
export const PLAYING_EXPERIENCE = 'PLAYING_EXPERIENCE';

export const FETCH_SHOPPING_CART_ITEMS = 'FETCH_SHOPPING_CART_ITEMS';
export const UPDATE_SHOPPING_CART_ITEMS = 'UPDATE_SHOPPING_CART_ITEMS';
export const FETCH_SHOPPING_CART_TAX_SUMMARY = 'FETCH_SHOPPING_CART_TAX_SUMMARY';
export const FETCH_SHOPPING_CART_TRANSACTION_SUMMARY = 'FETCH_SHOPPING_CART_TRANSACTION_SUMMARY';
export const SHOPPING_CART_CHECKOUT = 'SHOPPING_CART_CHECKOUT';
export const CREATE_SHOPPING_CART = 'CREATE_SHOPPING_CART';
export const FETCH_SHOPPING_CART_ITEMS_COUNT = 'FETCH_SHOPPING_CART_ITEMS_COUNT';

export const FETCH_ISP_AVAILABLE_SESSION_SLOTS = 'FETCH_ISP_AVAILABLE_SESSION_SLOTS';

export const ISP_RESCHEDULE_SESSION = 'ISP_RESCHEDULE_SESSION';

export const FETCH_SSP_ORDER_SUMMARY = 'FETCH_SSP_ORDER_SUMMARY';
export const FETCH_SSP_PAYOUT_LIST = 'FETCH_SSP_PAYOUT_LIST';
export const FETCH_SSP_EARNINGS = 'FETCH_SSP_EARNINGS';
export const FETCH_FUND_WITHDRAW_SETTINGS = 'FETCH_FUND_WITHDRAW_SETTINGS';
export const FETCH_BANK_ACCOUNTS = 'FETCH_BANK_ACCOUNTS';
export const SAVE_FUND_SETTINGS = 'SAVE_FUND_SETTINGS';
export const FETCH_MASTER_DATA_DAYS_OF_WEEK = 'FETCH_MASTER_DATA_DAYS_OF_WEEK';

export const ISP_FETCH_WORKING_DAYS = 'ISP_FETCH_WORKING_DAYS';
export const ISP_SAVE_WORKING_DAYS = 'ISP_SAVE_WORKING_DAYS';
export const ISP_FETCH_SPORTS_LIST = 'ISP_FETCH_SPORTS_LIST';

export const SET_BOOKING_CUT_OFF_TIME = 'SET_BOOKING_CUT_OFF_TIME';
export const ISP_VERIFY_BUSINESS_EMAIL = 'ISP_VERIFY_BUSINESS_EMAIL';
export const ISP_VERIFY_BUSINESS_EMAIL_OTP = 'ISP_VERIFY_BUSINESS_EMAIL_OTP';

export const ISP_VERIFY_EMAIL = 'ISP_VERIFY_EMAIL';
export const ISP_VERIFY_EMAIL_OTP = 'ISP_VERIFY_EMAIL_OTP';

export const ATHLETE_VERIFY_EMAIL = 'ATHLETE_VERIFY_EMAIL';
export const ATHLETE_VERIFY_EMAIL_OTP = 'ATHLETE_VERIFY_EMAIL_OTP';

export const ISP_FETCH_AVAILABLE_SESSION_TIME_SLOTS = 'ISP_FETCH_AVAILABLE_SESSION_TIME_SLOTS';

export const PARENT_VERIFY_EMAIL = 'PARENT_VERIFY_EMAIL';
export const PARENT_VERIFY_EMAIL_OTP = 'PARENT_VERIFY_EMAIL_OTP';

export const SSP_BOOKING_ACTION = 'SSP_BOOKING_ACTION';

export const FETCH_ISP_BOOKING_SCHEDULED_SESSIONS = 'FETCH_ISP_BOOKING_SCHEDULED_SESSIONS';
export const FETCH_WALLET_SUMMARY = 'FETCH_WALLET_SUMMARY';
export const UPDATE_ATHLETE_PAYMENT_METHOD = 'UPDATE_ATHLETE_PAYMENT_METHOD';
export const UPDATE_PARENT_PAYMENT_METHOD = 'UPDATE_PARENT_PAYMENT_METHOD';

export const FETCH_BILLING_ADDRESS = 'FETCH_BILLING_ADDRESS';
export const FETCH_SHIPPING_ADDRESS = 'FETCH_SHIPPING_ADDRESS';
export const UPDATE_BILLING_ADDRESS = 'UPDATE_BILLING_ADDRESS';
export const POST_INVITE_FRIENDS = 'POST_INVITE_FRIENDS';
export const UPDATE_SHIPPING_ADDRESS = 'UPDATE_SHIPPING_ADDRESS';
export const FETCH_PAYMENT_DETAILS = 'FETCH_PAYMENT_DETAILS';
export const CHARGE_CARD = 'CHARGE_CARD';
export const SAVE_PAYMENT_SOURCE = 'SAVE_PAYMENT_SOURCE';
export const DELETE_PAYMENT_SOURCE = 'DELETE_PAYMENT_SOURCE';
export const FETCH_PAYMENT_SUMMARY = 'FETCH_PAYMENT_SUMMARY';

export const ATHLETE_HANDLE_BOOKING_CHANGES = 'ATHLETE_HANDLE_BOOKING_CHANGES';
export const FETCH_ISP_ORDER_UPCOMMING_SESSIONS = 'FETCH_ISP_ORDER_UPCOMMING_SESSIONS';

export const SSP_CANCEL_FUTURE_SESSIONS = 'SSP_CANCEL_FUTURE_SESSIONS';

export const SSP_REPORT_ATHLETE = 'SSP_REPORT_ATHLETE';

export const REORDER = 'REORDER';
