export const PENDING = '_PENDING';
export const FULFILLED = '_FULFILLED';
export const REJECTED = '_REJECTED';

export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';
export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_COACH_IDS = 'UPDATE_COACH_IDS';
export const UPDATE_CAMP_IDS = 'UPDATE_CAMP_IDS';
export const UPDATE_FITNESS_BUSINESS_IDS = 'UPDATE_FITNESS_BUSINESS_IDS';
export const UPDATE_OTHER_IDS = 'UPDATE_OTHER_IDS';
export const UPDATE_ATHLETE_IDS = 'UPDATE_ATHLETE_IDS';
export const UPDATE_PARENT_IDS = 'UPDATE_PARENT_IDS';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_COUNTRIES = 'SET_COUNTRIES';
export const ADD_COUNTRY = 'ADD_COUNTRY';
export const CLEAR_COUNTRIES = 'CLEAR_COUNTRIES';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const ADD_PICTURE = 'ADD_PICTURE';
export const UPDATE_PICTURE = 'ADD_PICTURE';
export const CLEAR_PICTURE = 'CLEAR_PICTURE';
export const SET_IMAGES = 'SET_IMAGES';
export const UPDATE_IMAGE = 'SET_IMAGE';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';
export const ADD_IMAGES = 'ADD_IMAGES';
export const CLEAR_IMAGES = 'CLEAR_IMAGES';
export const SET_VIDEOS = 'SET_VIDEOS';
export const REMOVE_VIDEO = 'REMOVE_VIDEO';
export const ADD_VIDEOS = 'ADD_VIDEOS';
export const UPDATE_VIDEO = 'UPDATE_VIDEO';
export const CLEAR_VIDEOS = 'CLEAR_VIDEOS';
export const UPDATE_SPORT = 'UPDATE_SPORT';
export const CLEAR_SPORTS = 'CLEAR_SPORTS';
export const UPDATE_SPECIALIZATION = 'UPDATE_SPECIALITY';
export const ADD_NEW_SPORT = 'ADD_NEW_SPORT';
export const UPDATE_CERTIFICATION = 'UPDATE_CERTIFICATION';
export const CLEAR_CERTIFICATIONS = 'CLEAR_CERTIFICATIONS';
export const ADD_NEW_CERTIFICATION = 'ADD_NEW_CERTIFICATION';
export const UPDATE_DEGREE = 'UPDATE_DEGREE';
export const CLEAR_DEGREES = 'CLEAR_DEGREES';
export const ADD_NEW_DEGREE = 'ADD_NEW_DEGREE';
export const UPDATE_SKILLLEVEL = 'UPDATE_SKILLLEVEL';
export const CLEAR_SKILLLEVELS = 'CLEAR_SKILLLEVELS';
export const UPDATE_AGE = 'UPDATE_AGE';
export const CLEAR_AGES = 'CLEAR_AGES';
export const UPDATE_GENDER = 'UPDATE_GENDER';
export const CLEAR_GENDER = 'CLEAR_GENDER';
export const UPDATE_TRAINING = 'UPDATE_TRAINING';
export const CLEAR_TRAINING = 'CLEAR_TRAINING';
export const UPDATE_SERVICE = 'UPDATE_SERVICE';
export const CLEAR_SERVICE = 'CLEAR_SERVICE';
export const UPDATE_LISTING = 'UPDATE_LISTING';
export const CLEAR_LISTING = 'CLEAR_LISTING';
export const ADD_SESSION = 'ADD_SESSION';
export const UPDATE_SESSION = 'UPDATE_SESSION';

export const CLEAR_SESSION = 'CLEAR_SESSION';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const CLEAR_ACCOUNT = 'CLEAR_ACCOUNT';
export const UPDATE_BOOKING_PREFERENCES = 'UPDATE_BOOKING_PREFERENCES';
export const CLEAR_BOOKING_PREFERENCES = 'CLEAR_BOOKING_PREFERENCES';
export const UPDATE_BUSINESS_MODEL = 'UPDATE_BUSINESS_MODEL';
export const CLEAR_BUSINESS_MODEL = 'CLEAR_BUSINESS_MODEL';
export const UPDATE_EVENT = 'UPDATE_EVENT';
export const CLEAR_EVENTS = 'CLEAR_EVENTS';
export const ADD_EVENTS = 'ADD_EVENTS';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const CLEAR_LOCATIONS = 'CLEAR_LOCATIONS';
export const ADD_LOCATION = 'ADD_LOCATION';
export const UPDATE_PAYOUT_OPTION = 'UPDATE_PAYOUT_OPTION';
export const CLEAR_PAYOUT_OPTION = 'CLEAR_PAYOUT_OPTION';
export const UPDATE_BANK_DETAILS = 'UPDATE_BANK_DETAILS';
export const CLEAR_BANK_DETAILS = 'CLEAR_BANK_DETAILS';
export const UPDATE_PAYPAL_DETAILS = 'UPDATE_PAYPAL_DETAILS';
export const CLEAR_PAYPAL_DETAILS = 'CLEAR_PAYPAL_DETAILS';
export const UPDATE_PRICE = 'UPDATE_PRICE';
export const CLEAR_PRICES = 'CLEAR_PRICES';
export const ADD_PRICE = 'ADD_PRICE';
export const UPDATE_TRAVEL_PREFERENCES = 'UPDATE_TRAVEL_PREFERENCES';
export const CLEAR_TRAVEL_PREFERENCES = 'CLEAR_TRAVEL_PREFERENCES';

export const UPDATE_AGES_PRICING = 'UPDATE_AGES_PRICING';
export const UPDATE_SKILLLEVELS_PRICING = 'UPDATE_SKILLLEVELS_PRICING';
export const ADD_AGES_PRICING = 'ADD_AGES_PRICING';
export const ADD_SKILLLEVELS_PRICING = 'ADD_SKILLLEVELS_PRICING';

export const ADD_MESSAGE_LABEL = 'ADD_MESSAGE_LABEL';
export const FETCH_MESSAGE_LABEL = 'FETCH_MESSAGE_LABEL';
export const DELETE_MESSAGE_LABEL = 'DELETE_MESSAGE_LABEL';
export const CLEAR_MESSAGE_LABELS = 'CLEAR_MESSAGE_LABELS';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const CLEAR_SENT_MESSAGE_STATUS = 'CLEAR_SENT_MESSAGE_STATUS';

export const FETCH_DRAFT_MESSAGES = 'FETCH_DRAFT_MESSAGES';
export const SAVE_MESSAGE_DRAFTS = 'SAVE_MESSAGE_DRAFT';
export const CLEAR_DRAFT_MESSAGE_STATUS = 'CLEAR_DRAFT_MESSAGE_STATUS';
export const CLEAR_DRAFT_MESSAGES = 'CLEAR_DRAFT_MESSAGES';

export const CHANGE_MESSAGING_PROFILE = 'CHANGE_MESSAGING_PROFILE';

export const ADD_DISCOUNT = 'ADD_DISCOUNT';

export const UPDATE_SESSION_NAME = 'UPDATE_SESSION_NAME';
export const CLEAR_SESSION_NAME = 'CLEAR_SESSION_NAME';

export const SET_STATES = 'SET_STATES';
export const ADD_STATE = 'ADD_STATE';
export const CLEAR_STATES = 'CLEAR_STATES';

export const UPDATE_BUSINESS = 'UPDATE_BUSINESS';
export const CLEAR_BUSINESS = 'CLEAR_BUSINESS';

export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const UPDATE_PHONES = 'UPDATE_PHONES';
export const ADD_PHONE = 'ADD_PHONE';
export const CLEAR_CONTACT = 'CLEAR_CONTACT';

export const SET_SESSIONS = 'SET_SESSIONS';
export const REMOVE_SESSION = 'REMOVE_SESSION';
export const REMOVE_LOCATION = 'REMOVE_LOCATION';

export const REMOVE_EVENT = 'REMOVE_EVENT';

export const ADD_SKILLLEVEL = 'ADD_SKILLLEVEL';
export const REMOVE_DISCOUNT = 'REMOVE_DISCOUNT';

export const FETCH_SELECTED_THREAD = 'FETCH_SELECTED_THREAD';
export const CLEAR_SELECTED_THREAD = 'CLEAR_SELECTED_THREAD';
export const FETCH_REWARDS = 'FETCH_REWARDS';
export const FETCH_PROFILE = 'FETCH_PROFILE';
export const FETCH_SPORTS = 'FETCH_SPORTS';
export const FETCH_SPORTS_LIST = 'FETCH_SPORTS_LIST';
export const FETCH_CERTIFICATIONS_LIST = 'FETCH_CERTIFICATIONS_LIST';
export const FETCH_DEGREES_LIST = 'FETCH_DEGREES_LIST';
export const FETCH_INSTITUTIONS_LIST = 'FETCH_INSTITUTIONS_LIST';
export const SET_LOCATIONS = 'SET_LOCATIONS';
export const SET_TRAINING = 'SET_TRAINING';
export const SET_SERVICE = 'SET_SERVICE';
export const SET_GENDER = 'SET_GENDER';
export const SET_AGES = 'SET_AGES';
export const SET_SKILLS = 'SET_SKILLS';
export const SET_PRICING = 'SET_PRICING';
export const SET_SPORTS = 'SET_SPORTS';
export const SET_CERTIFICATIONS = 'SET_CERTIFICATIONS';
export const SET_DEGREE = 'SET_DEGREE';
export const SET_BUSINESS = 'SET_BUSINESS';
export const SET_LISTING = 'SET_LISTING';
export const FETCH_REWARDS_STATS = 'FETCH_REWARDS_STATS';
export const FETCH_SESSION_STATS = 'FETCH_SESSION_STATS';
export const FETCH_REVIEW_STATS = 'FETCH_REVIEW_STATS';
export const FETCH_EARNING_STATS = 'FETCH_EARNING_STATS';

export const UPDATE_PROFILE_DATA = 'UPDATE_PROFILE_DATA';

export const FETCH_USER_PROFILES = 'FETCH_USER_PROFILES';
export const CLEAR_USER_PROFILES = 'CLEAR_USER_PROFILES';

export const ARCHIVE_MESSAGE_THREAD = 'ARCHIVE_MESSAGE_THREAD';
export const TRASH_MESSAGE_THREAD = 'TRASH_MESSAGE_THREAD';
export const STAR_MESSAGE_THREAD = 'STAR_MESSAGE_THREAD';
export const UPDATE_MESSAGE_THREAD_LABELS = 'UPDATE_MESSAGE_THREAD_LABELS';

export const GET_UPDATED_SELECTED_THREAD = 'GET_UPDATED_SELECTED_THREAD';

export const LOCATION_URL_CHANGE = 'LOCATION_URL_CHANGE';
export const POST_PROFILE = 'POST_PROFILE';
export const SUCCESS = 'SUCCESS';

export const CLEAR_SPORTS_LIST = 'CLEAR_SPORTS_LIST';
export const SET_SPORTS_LIST = 'SET_SPORTS_LIST';
export const CLEAR_DEGREES_LIST = 'CLEAR_DEGREES_LIST';
export const SET_DEGREES_LIST = 'SETDEGREES_LIST';
export const CLEAR_INSTITUTIONS_LIST = 'CLEAR_INSTITUTIONS_LIST';
export const SET_INSTITUTIONS_LIST = 'SET_INSTITUTIONS_LIST';
export const CLEAR_CERTIFICATIONS_LIST = 'CLEAR_CERTIFICATIONS_LIST';
export const SET_CERTIFICATIONS_LIST = 'SET_CERTIFICATIONS_LIST';

export const FETCH_CANCELLATION_POLICIES = 'FETCH_CANCELLATION_POLICIES';
export const CLEAR_CANCELLATION_POLICIES = 'CLEAR_CANCELLATION_POLICIES';

export const FETCH_SKILLS_LIST = 'FETCH_SKILLS_LIST';
export const CLEAR_SKILLS_LIST = 'CLEAR_SKILLS_LIST';

export const FETCH_AGES_LIST = 'FETCH_AGES_LIST';
export const CLEAR_AGES_LIST = 'CLEAR_AGES_LIST';

export const FETCH_TRAINING_LIST = 'FETCH_TRAINING_LIST';
export const CLEAR_TRAINING_LIST = 'CLEAR_TRAINING_LIST';
export const FETCH_SERVICES_LIST = 'FETCH_SERVICES_LIST';
export const CLEAR_SERVICES_LIST = 'CLEAR_SERVICES_LIST';
export const INVITE_USERS = 'INVITE_USERS';
export const FETCH_REWARDS_HISTORY = 'FETCH_REWARDS_HISTORY';
export const FILTER_CHANGE_REWARDS_HISTORY = 'FILTER_CHANGE_REWARDS_HISTORY';
export const FETCH_USER_IDS = 'FETCH_USER_IDS';

export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const FETCH_STATES = 'FETCH_STATES';

export const FETCH_LOCATIONS = 'FETCH_LOCATIONS';
export const FETCH_SESSIONS = 'FETCH_SESSIONS';
export const FETCH_EVENTS = 'FETCH_EVENTS';

export const FETCH_MESSAGE_THREADS = 'FETCH_MESSAGE_THREADS';
export const FETCH_MESSAGES_METADATA = 'FETCH_MESSAGES_METADATA';

export const THREAD_LIST_PAGE_CHANGE = 'THREAD_LIST_PAGE_CHANGE';

export const POLYGLOT_SET_LANGUAGE = '@@polyglot/SET_LANGUAGE';

export const POLL_MESSAGES_METADATA = 'POLL_MESSAGES_METADATA';
export const CANCEL_POLL_MESSAGES_METADATA = 'CANCEL_POLL_MESSAGES_METADATA';
export const SET_RATING = 'SET_RATING';
export const UPDATE_OFFER_TERMINOLOGY = 'UPDATE_OFFER_TERMINOLOGY';

export const ACTIVATE_DISCOUNT = 'ACTIVATE_DISCOUNT';
export const UPDATE_CANCELLATION_POLICY = 'UPDATE_CANCELLATION_POLICY';
export const CLEAR_CANCELLATION_POLICY = 'CLEAR_CANCELLATION_POLICY';

export const UPDATE_CURRENCY = 'UPDATE_CURRENCY';
export const CLEAR_CURRENCY = 'CLEAR_CURRENCY';

export const SEARCH_MESSAGE_RECIPIENTS = 'SEARCH_MESSAGE_RECIPIENTS';
export const UPDATE_THREAD_READ_STATUS = 'UPDATE_THREAD_READ_STATUS';

export const VERIFY_NICKNAME = 'VERIFY_NICKNAME';
export const FETCH_NICKNAMES = 'FETCH_NICKNAMES';

export const UPDATE_DEFAULT_SESSION = 'UPDATE_DEFAULT_SESSION';
export const UPDATE_OVERRIDE_SESSION_LENGTH = 'UPDATE_OVERRIDE_SESSION_LENGTH';
export const UPDATE_OVERRIDE_BUFFER_LENGTH = 'UPDATE_OVERRIDE_BUFFER_LENGTH';
export const FETCH_TIMEZONES = 'FETCH_TIMEZONES';
export const SSP_SET_NICKNAME = 'SSP_SET_NICKNAME';

export const VALIDATE_BANK_PAYOUT_DETAILS = 'VALIDATE_BANK_PAYOUT_DETAILS';
export const SSP_BANK_PAYOUT_DETAILS_SUBMIT = 'SSP_BANK_PAYOUT_DETAILS_SUBMIT';
export const SSP_VALIDATE_PAYPAL_SETTINGS = 'SSP_VALIDATE_PAYPAL_SETTINGS';
export const SSP_PAYPAL_SETTINGS_SUBMIT = 'SSP_PAYPAL_SETTINGS_SUBMIT';
export const SSP_PAYOUT_DETAILS_SUBMIT = 'SSP_PAYOUT_DETAILS_SUBMIT';
export const SSP_VALIDATE_PAYOUT_DETAILS = 'SSP_VALIDATE_PAYOUT_DETAILS';
export const SSP_ACCOUNT_DETAILS_SUBMIT = 'SSP_ACCOUNT_DETAILS_SUBMIT';
export const SSP_VALIDATE_ACCOUNT_DETAILS = 'SSP_VALIDATE_ACCOUNT_DETAILS';
export const SSP_VALIDATE_BOOKING_PREFERENCE = 'SSP_VALIDATE_BOOKING_PREFERENCE';
export const SSP_BOOKING_PREFERENCE_SUBMIT = 'SSP_BOOKING_PREFERENCE_SUBMIT';
export const SSP_VALIDATE_BUSINESS_MODEL = 'SSP_VALIDATE_BUSINESS_MODEL';
export const SSP_BUSINESS_MODEL_SUBMIT = 'SSP_BUSINESS_MODEL_SUBMIT';
export const SSP_BUILD_PROFILE_SUBMIT = 'SSP_BUILD_PROFILE_SUBMIT';
export const SSP_VALIDATE_BUILD_PROFILE = 'SSP_VALIDATE_BUILD_PROFILE';
export const SSP_VALIDATE_TRAINING_PREFERENCE = 'SSP_VALIDATE_TRAINING_PREFERENCE';
export const SSP_TRAINING_PREFERENCE_SUBMIT = 'SSP_TRAINING_PREFERENCE_SUBMIT';

export const SSP_TRAINING_LOCATION_SUBMIT = 'SSP_TRAINING_LOCATION_SUBMIT';
export const SSP_VALIDATE_TRAINING_LOCATION = 'SSP_VALIDATE_TRAINING_LOCATION';

export const SSP_VALIDATE_TRAVEL_PREFERENCE = 'SSP_VALIDATE_TRAVEL_PREFERENCE';
export const SSP_TRAVEL_PREFERENCE_SUBMIT = 'SSP_TRAVEL_PREFERENCE_SUBMIT';
export const SSP_LISTING_SUBMIT = 'SSP_LISTING_SUBMIT';
export const SSP_VALIADATE_LISTING = 'SSP_VALIADATE_LISTING';
export const SSP_VALIDATE_PHOTOS_AND_VIDEOS = 'SSP_VALIDATE_PHOTOS_AND_VIDEOS';
export const SSP_PHOTOS_AND_VIDEOS_SUBMIT = 'SSP_PHOTOS_AND_VIDEOS_SUBMIT';

export const SSP_VALIDATE_SESSION_NAME = 'SSP_VALIDATE_SESSION_NAME';
export const SSP_SESSION_NAME_SUBMIT = 'SSP_SESSION_NAME_SUBMIT';
export const SSP_VALIDATE_SESSION = 'SSP_VALIDATE_SESSION';
export const SSP_SESSION_SUBMIT = 'SSP_SESSION_SUBMIT';

export const SSP_VALIDATE_EVENTS = 'SSP_VALIDATE_EVENTS';
export const SSP_SUBMIT_EVENTS = 'SSP_SUBMIT_EVENTS';

// Search Filter

export const POST_SEARCH_FILTER = 'POST_SEARCH_FILTER';

export const UPDATE_SEARCH_FILTER = 'UPDATE_SEARCH_FILTER';
export const CLEAR_SEARCH_FILTER = 'CLEAR_SEARCH_FILTER';

// Search String
export const UPDATE_SEARCH_KEY = 'UPDATE_SEARCH_KEY';
export const CLEAR_SEARCH_KEY = 'CLEAR_SEARCH_KEY';

// Location String
export const UPDATE_LOCATION_KEY = 'UPDATE_LOCATION_KEY';
export const CLEAR_LOCATION_KEY = 'CLEAR_LOCATION_KEY';

// Athlete
export const UPDATE_ATHLETE = 'UPDATE_ATHLETE';
export const CLEAR_ATHLETE = 'CLEAR_ATHLETE';

// Distance
export const UPDATE_FILTER_DISTANCE = 'UPDATE_FILTER_DISTANCE';
export const CLEAR_FILTER_DISTANCE = 'CLEAR_FILTER_DISTANCE';

// Instand Book
export const UPDATE_INSTAND_BOOK = 'UPDATE_INSTAND_BOOK';
export const CLEAR_INSTAND_BOOK = 'CLEAR_INSTAND_BOOK';

// Price
export const UPDATE_FILTER_PRICE = 'UPDATE_FILTER_PRICE';
export const CLEAR_FILTER_PRICE = 'CLEAR_FILTER_PRICE';

// SortBy
export const UPDATE_FILTER_SORTBY = 'UPDATE_FILTER_SORTBY';
export const CLEAR_FILTER_SORTBY = 'CLEAR_FILTER_SORTBY';

// Trainer
export const UPDATE_TRAINER = 'UPDATE_TRAINER';
export const CLEAR_TRAINER = 'CLEAR_TRAINER';

// Search result
export const UPDATE_SELECTED_RESULT = 'UPDATE_SELECTED_RESULT';
export const CLEAR_SELECTED_RESULT = 'CLEAR_SELECTED_RESULT';

export const UPDATE_FILTER = 'UPDATE_FILTER';
export const CLEAR_FILTER = 'CLEAR_FILTER';

export const SET_STATE = 'SET_STATE';
export const MARKER_CLICK = 'MARKER_CLICK';
export const ADD_MARKER = 'ADD_MARKER';

// For SSP Details Page - Injected by SD Sondhi

export const FETCH_SSP_SESSIONS = 'FETCH_SSP_SESSIONS';
export const FETCH_SSP_PROFILEDATA = 'FETCH_SSP_PROFILEDATA';
export const LOCATION_FILTER = 'LOCATION_FILTER';
export const FACILITY_FILTER = 'FACILITY_FILTER';
export const SPECIALITY_FILTER = 'SPECIALITY_FILTER';
export const SERVICE_FILTER = 'SERVICE_FILTER';
export const SKILL_LEVEL_FILTER = 'SKILL_LEVEL_FILTER';
export const AGE_GROUP_FILTER = 'AGE_GROUP_FILTER';
export const GENDER_FILTER = 'GENDER_FILTER';

// End of Injection ---------------------------

export const DELETE_MESSAGE_ATTACHMENT = 'DELETE_MESSAGE_ATTACHMENT';
export const SSP_VALIDATE_DISCOUNT = 'SSP_VALIDATE_DISCOUNT';
export const SSP_DISCOUNT_SUBMIT = 'SSP_DISCOUNT_SUBMIT';
export const RESET_DISCOUNT = 'RESET_DISCOUNT';
export const SET_NEW_PROFILE = 'SET_NEW_PROFILE';
export const CREATE_NEW_PROFILE = 'CREATE_NEW_PROFILE';

export const SSP_VALIDATE_PRICING = 'SSP_VALIDATE_PRICING';
export const SSP_VALIDATE_MULTIPLE_PRICING = 'SSP_VALIDATE_MULTIPLE_PRICING';
export const SSP_PRICING_SUBMIT = 'SSP_PRICING_SUBMIT';
export const CHANGE_PROFILE_UPDATE_STATUS = 'CHANGE_PROFILE_UPDATE_STATUS';
export const UPLOAD_ACTION_PICTURES = 'UPLOAD_ACTION_PICTURES';
export const SET_ACTION_PICTURES = 'SET_ACTION_PICTURES';
export const DELETE_ACTION_PICTURE = 'DELETE_ACTION_PICTURE';
export const UPDATE_ACTION_PICTURE = 'UPDATE_ACTION_PICTURE';
export const UPLOAD_ACTION_VIDEOS = 'UPLOAD_ACTION_VIDEOS';
export const SET_ACTION_VIDEOS = 'SET_ACTION_VIDEOS';
export const DELETE_ACTION_VIDEO = 'DELETE_ACTION_VIDEO';
export const ACTION_VIDEOS_UPLOAD_PROGRESS = 'ACTION_VIDEOS_UPLOAD_PROGRESS';
export const UPDATE_NICKNAME = 'UPDATE_NICKNAME';
export const SSP_SET_PRESENT_NICKNAME = 'SSP_SET_PRESENT_NICKNAME';
export const SET_DISPLAY_PICTURE = 'SET_DISPLAY_PICTURE';
export const POST_ACTION_IMAGES = 'POST_ACTION_IMAGES';
export const POST_ACTION_VIDEOS = 'POST_ACTION_VIDEOS';
export const SET_CITIES = 'SET_CITIES';
export const FETCH_CITIES = 'FETCH_CITIES';
export const ADD_CITIES = 'ADD_CITIES';
export const CLEAR_CITIES = 'CLEAR_CITIES';

export const SSP_VALIDATE_TRAINING_LOCATIONS = 'SSP_VALIDATE_TRAINING_LOCATIONS';
export const SSP_TRAINING_LOCATIONS_SUBMIT = 'SSP_TRAINING_LOCATIONS_SUBMIT';
export const SET_PAYPAL_VERIFICATION_STATUS = 'SET_PAYPAL_VERIFICATION_STATUS';
export const VERIFY_PAYAPAL_EMAIL = 'VERIFY_PAYAPAL_EMAIL';
export const VERIFY_PAYAPAL_PIN = 'VERIFY_PAYAPAL_PIN';
export const FETCH_GEO_LOCATION = 'FETCH_GEO_LOCATION';

export const UPDATE_CURRENT_SPORT = 'UPDATE_CURRENT_SPORT';
export const SET_CURRENT_SPORT = 'SET_CURRENT_SPORT';
export const CLEAR_CURRENT_SPORT = 'CLEAR_CURRENT_SPORT';

export const UPDATE_CURRENT_TERMINOLOGY = 'UPDATE_CURRENT_TERMINOLOGY';
export const UPDATE_CURRENT_SPECIALIZATIONS = 'UPDATE_CURRENT_SPECIALIZATIONS';

export const UPDATE_UNI_DEGREE = 'UPDATE_UNI_DEGREE';
export const CLEAR_UNI_DEGREE = 'CLEAR_UNI_DEGREE';
export const NEW_DEGREE_VALIDATION = 'NEW_DEGREE_VALIDATION';
export const NEW_DEGREE_SUBMIT = 'NEW_DEGREE_SUBMIT';
export const ADD_DEGREE = 'ADD_DEGREE';

export const FETCH_CURRENT_SPORT = 'FETCH_CURRENT_SPORT';
export const DELETE_SPORT = 'DELETE_SPORT';
export const POST_CURRENT_SPORT = 'POST_CURRENT_SPORT';
export const ADD_NEW_DEGREE_TO_DB = 'ADD_NEW_DEGREE_TO_DB';
export const ADD_NEW_INSTITUTION_TO_DB = 'ADD_NEW_INSTITUTION_TO_DB';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const DEACTIVATE_ACCOUNT = 'DEACTIVATE_ACCOUNT';

export const SET_SPORTS_DEGREE = 'SET_SPORTS_DEGREE';
export const ADD_SPORTS_DEGREE = 'ADD_SPORTS_DEGREE';
export const CLEAR_SPORTS_DEGREES = 'CLEAR_SPORTS_DEGREES';
export const REMOVE_SPORTS_DEGREE = 'REMOVE_SPORTS_DEGREE';
export const REMOVE_UNI_DEGREE = 'REMOVE_UNI_DEGREE';
export const FETCH_GEN_CERTIFICATIONS_LIST = 'FETCH_GEN_CERTIFICATIONS_LIST';
export const CLEAR_GEN_CERTIFICATIONS_LIST = 'CLEAR_GEN_CERTIFICATIONS_LIST';
export const UPDATE_NEW_CERTIFICATION = 'UPDATE_NEW_CERTIFICATION';
export const CLEAR_NEW_CERTIFICATION = 'CLEAR_NEW_CERTIFICATION';
export const ADD_NEW_CERTIFICATION_TO_DB = 'ADD_NEW_CERTIFICATION_TO_DB';
export const ADD_NEW_GEN_CERTIFICATION = 'ADD_NEW_GEN_CERTIFICATION';
export const SET_GEN_CERTIFICATIONS = 'SET_GEN_CERTIFICATIONS';
export const REMOVE_GEN_CERTIFICATION = 'REMOVE_GEN_CERTIFICATION';
export const CLEAR_GEN_CERTIFICATIONS = 'CLEAR_GEN_CERTIFICATIONS';
export const NEW_CERTIFICATION_VALIDATION = 'NEW_CERTIFICATION_VALIDATION';
export const NEW_CERTIFICATION_SUBMIT = 'NEW_CERTIFICATION_SUBMIT';
export const ADD_NEW_SPORT_CERTIFICATION = 'ADD_NEW_SPORT_CERTIFICATION';
export const REMOVE_SPORT_CERTIFICATION = 'REMOVE_SPORT_CERTIFICATION';
export const CLEAR_NEW_CERTIFICATION_VALIDATION = 'CLEAR_NEW_CERTIFICATION_VALIDATION';
export const FETCH_GEN_AWARDS_LIST = 'FETCH_GEN_AWARDS_LIST';
export const CLEAR_GEN_AWARDS_LIST = 'CLEAR_GEN_AWARDS_LIST';
export const UPDATE_UNI_AWARD = 'UPDATE_UNI_AWARD';
export const CLEAR_UNI_AWARD = 'CLEAR_UNI_AWARD';
export const NEW_AWARD_VALIDATION = 'NEW_AWARD_VALIDATION';
export const NEW_AWARD_SUBMIT = 'NEW_AWARD_SUBMIT';
export const CLEAR_NEW_AWARDS_VALIDATION = 'CLEAR_NEW_AWARDS_VALIDATION';
export const ADD_NEW_GEN_AWARD = 'ADD_NEW_GEN_AWARD';
export const SET_GEN_AWARDS = 'SET_GEN_AWARDS';
export const CLEAR_GEN_AWARDS = 'CLEAR_GEN_AWARDS';
export const REMOVE_GEN_AWARD = 'REMOVE_GEN_AWARD';
export const SET_SPORTS_AWARDS = 'SET_SPORTS_AWARDS';
export const ADD_SPORTS_AWARD = 'ADD_SPORTS_AWARD';
export const REMOVE_SPORTS_AWARD = 'REMOVE_SPORTS_AWARD';
export const CLEAR_SPORTS_AWARDS = 'CLEAR_SPORTS_AWARDS';
export const SET_SPORTS_AWARDS_LIST = 'SET_SPORTS_AWARDS_LIST';
export const CLEAR_SPORTS_AWARDS_LIST = 'CLEAR_SPORTS_AWARDS_LIST';
export const ADD_NEW_AWARD_TO_DB = 'ADD_NEW_AWARD_TO_DB';
export const UPDATE_NEW_AFFILIATION = 'UPDATE_NEW_AFFILIATION';
export const CLEAR_NEW_AFFILIATION = 'CLEAR_NEW_AFFILIATION';
export const SET_GEN_AFFILIATION = 'SET_GEN_AFFILIATION';
export const SET_SPORTS_AFFILIATION = 'SET_SPORTS_AFFILIATION';
export const ADD_NEW_GEN_AFFILIATION = 'ADD_NEW_GEN_AFFILIATION';
export const ADD_NEW_SPORTS_AFFILIATION = 'ADD_NEW_SPORTS_AFFILIATION';
export const REMOVE_GEN_AFFILIATION = 'REMOVE_GEN_AFFILIATION';
export const REMOVE_SPORTS_AFFILIATION = 'REMOVE_SPORTS_AFFILIATION';
export const CLEAR_GEN_AFFILIATION = 'CLEAR_GEN_AFFILIATION';
export const CLEAR_SPORTS_AFFILIATION = 'CLEAR_SPORTS_AFFILIATION';
export const UPDATE_NEW_TOOLS = 'UPDATE_NEW_TOOLS';
export const CLEAR_NEW_TOOLS = 'CLEAR_NEW_TOOLS';
export const ADD_NEW_GEN_TOOL = 'ADD_NEW_GEN_TOOL';
export const ADD_NEW_SPORT_TOOL = 'ADD_NEW_SPORT_TOOL';
export const SET_GEN_TOOLS = 'SET_GEN_TOOLS';
export const SET_SPORTS_TOOLS = 'SET_SPORTS_TOOLS';
export const REMOVE_GEN_TOOL = 'REMOVE_GEN_TOOL';
export const REMOVE_SPORTS_TOOL = 'REMOVE_SPORTS_TOOL';
export const CLEAR_GEN_TOOLS = 'CLEAR_GEN_TOOLS';
export const CLEAR_SPORTS_TOOL = 'CLEAR_SPORTS_TOOL';
export const ADD_NEW_TOOL_TO_DB = 'ADD_NEW_TOOL_TO_DB';
export const SET_SPORTS_TOOL_LIST = 'SET_SPORTS_TOOL_LIST';
export const FETCH_GEN_TOOL_LIST = 'FETCH_GEN_TOOL_LIST';
export const CLEAR_GEN_TOOLS_LIST = 'CLEAR_GEN_TOOLS_LIST';
export const CLEAR_SPORTS_TOOLS_LIST = 'CLEAR_SPORTS_TOOLS_LIST';
export const SET_SPORTS_DEGREE_LIST = 'SET_SPORTS_DEGREE_LIST';
export const CLEAR_SPORTS_DEGREES_LIST = 'CLEAR_SPORTS_DEGREES_LIST';
export const POST_SESSIONS = 'POST_SESSIONS';
export const DELETE_SESSION = 'DELETE_SESSION';
export const CHANGE_SPORT_UPDATE_STATUS = 'CHANGE_SPORT_UPDATE_STATUS';

export const POST_EVENTS = 'POST_EVENTS';
export const DELETE_EVENT = 'DELETE_EVENT';
export const SET_SPORTS_STORE = 'SET_SPORTS_STORE';
export const SET_TRAVEL_PREFERENCES = 'SET_TRAVEL_PREFERENCES';
export const SET_CONTACT = 'SET_CONTACT';
export const SET_BUSINESS_MODEL = 'SET_BUSINESS_MODEL';
export const SET_BOOKING_PREFERENCES = 'SET_BOOKING_PREFERENCES';
export const SET_CANCELATION_POLICY = 'SET_CANCELATION_POLICY';
export const SET_PAYOUT_OPTION = 'SET_PAYOUT_OPTION';
export const SET_CURRENCY = 'SET_CURRENCY';
export const SET_BANK_DETAILS = 'SET_BANK_DETAILS';
export const SET_PAYPAL_DETAILS = 'SET_PAYPAL_DETAILS';

export const SAVE_DATA_ON_NEXT = 'SAVE_DATA_ON_NEXT';
export const CLEAR_SAVE_DATA_ON_NEXT = 'CLEAR_SAVE_DATA_ON_NEXT';

export const ACTIVATE_NEW_PROFILE = 'ACTIVATE_NEW_PROFILE';
export const ACTIVATE_SPORT = 'ACTIVATE_SPORT';
export const ACTIVATE_SPORT_AND_PROFILE = 'ACTIVATE_SPORT_AND_PROFILE';
export const CHANGE_PROFILE_ACTIVATION_STATUS = 'CHANGE_PROFILE_ACTIVATION_STATUS';

export const CLEAR_SESSION_VALIDATION = 'CLEAR_SESSION_VALIDATION';
export const DELETE_DISCOUNT = 'DELETE_DISCOUNT';

export const CONTACTSSP_DETAIL = 'CONTACTSSP_DETAIL';
export const FETCH_SPORT_SUGGESTION = 'FETCH_SPORT_SUGGESTION';

export const FETCH_SPORT_SUGGESTION_ES = 'FETCH_SPORT_SUGGESTION_ES';

export const FETCH_LOCATION_SUGGESTION = 'FETCH_LOCATION_SUGGESTION';

export const FETCH_LOCATION_SUGGESTION_ES = 'FETCH_LOCATION_SUGGESTION_ES';

export const FETCH_ELASTIC_SEARCH_DATA = 'FETCH_ELASTIC_SEARCH_DATA';

export const FETCH_LOCATION_REVERSE_LOOKUP_DATA = 'FETCH_LOCATION_REVERSE_LOOKUP_DATA';

export const CHANGE_SELECTED_LOCATION = 'CHANGE_SELECTED_LOCATION';

export const CHANGE_SELECTED_PROFILE = 'CHANGE_SELECTED_PROFILE';

export const FETCH_POPULAR_SPORTS = 'FETCH_POPULAR_SPORTS';

export const UPDATE_SPORTS_HIT_COUNT = 'UPDATE_SPORTS_HIT_COUNT';

export const UPDATE_BROWSER_GPS_PLUGIN_DATA = 'UPDATE_BROWSER_GPS_PLUGIN_DATA';

export const FETCH_NEARBY_LOCATIONS = 'FETCH_NEARBY_LOCATIONS';

export const FETCH_DISCOUNT_RATES = 'FETCH_DISCOUNT_RATES';

export const FETCH_SHOPPING_CART_ITEMS = 'FETCH_SHOPPING_CART_ITEMS';
export const UPDATE_SHOPPING_CART_ITEMS = 'UPDATE_SHOPPING_CART_ITEMS';
export const FETCH_SHOPPING_CART_TAX_SUMMARY = 'FETCH_SHOPPING_CART_TAX_SUMMARY';
export const SHOPPING_CART_CHECKOUT = 'SHOPPING_CART_CHECKOUT';
export const CREATE_SHOPPING_CART = 'CREATE_SHOPPING_CART';

export const SIGN_UP = 'SIGN_UP';
export const LOGIN = 'LOGIN';
export const VERIFY_OTP = 'VERIFY_OTP';
export const RESEND_EMAIL_VERIFICATION_OTP = 'RESEND_EMAIL_VERIFICATION_OTP';
export const CHECK_EMAIL_AVAILABILITY = 'CHECK_EMAIL_AVAILABILITY';
export const FETCH_BASIC_USER_INFO = 'FETCH_BASIC_USER_INFO';
export const FETCH_TOS = 'FETCH_TOS';
export const LOGOUT = 'LOGOUT';

export const FETCH_ELASTIC_SEARCH_DATA_SORTED = 'FETCH_ELASTIC_SEARCH_DATA_SORTED';

// No Result Found from Search Page
export const REGISTER_SERVICE_PROVIDERS_AVAILABILITY = 'REGISTER_SERVICE_PROVIDERS_AVAILABILITY';
// Sports List Todo: This might be duplicate from other.
export const AVAILABLE_SPORTS_LIST = 'AVAILABLE_SPORTS_LIST';
export const POST_SEND_COUPON = 'POST_SEND_COUPON';
